version: "3"

services:
  mindlogic-melgan-nips:
    build:
      context: .
    image: mindlogic-melgan-nips
    networks: ["mindlogic-network"]
    restart: always
    ports:
      - "6003:6003"
    environment:
      - CUDA_VISIBLE_DEVICES=2
    env_file:
      - "./.env"
    volumes:
      - "./:/app"

networks: { mindlogic-network: {} }
